sudo: required

services:
- docker

arch:
  repos:
  - theapps=https://vicr123.github.io/repo/arch/$arch/
  packages:
  - git
  - kwidgetsaddons
  - xdg-utils
  - wmctrl
  - kwin
  - networkmanager
  - xorg-xbacklight
  - redshift
  - libcups
  - qt5-base
  - ts-qtplatform
  - qt5-charts
  - qt5-location
  - kscreen
  - ts-bt
  - ts-bugreport
  script:
  - "./travis/build.sh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
