sudo: required

services:
- docker

arch:
  repos:
  - theapps=https://packages.vicr123.com/arch/$arch/
  packages:
  - git
  - kwidgetsaddons
  - xdg-utils
  - wmctrl
  - kwin
  - networkmanager
  - xorg-xbacklight
  - redshift
  - libcups
  - qt5-base
  - ts-qtplatform
  - qt5-charts
  - qt5-location
  - kscreen
  - ts-bt
  - ts-bugreport
  - base-devel
  - qt5-tools
  script:
  - "./travis/build.sh"
  - "./travis/publish.sh"

after_success:
  
script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

